# Generated by Django 4.2.16 on 2024-10-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='decription',
            new_name='description',
        ),
    ]
